GAA_KW_value((int), number_of_iterations)
    GAA_KW_value((double), converge_threshold)
        GAA_KW_cref((Eigen::MatrixXd), weight_matrix)
            GAA_KW_cref((gaa::Collinearity_condition_solver),
                        collinearity_condition_solver)
                GAA_KW_value((double), gt_threshold)
                    GAA_KW_value((double), lt_threshold)
                        GAA_KW_value((bool), ignore_first_line)
                            GAA_KW_value((char), separator)
                                GAA_KW_value((bool), trim_string)
                                    GAA_KW_value((int), stream_precision)
