/*
This is infrastructure for hetero container, the class Any is a wrapper of
std::any, but you can invoke many pre-defined member functions without knowing
its actual type.

Behaviour of member function is defined is compile time, but its error always
occurs in runtime. The class Any using a Vtable to combine runtime and compile
time, it get its Vtable (corresponding to an actual type) when is constructed.

Any ( storage T ) -> (ref to)) Vtable <= (generated by) Vtable::init<T>()
                     ^~~~~~~~~~~~~~~~    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                     |              control by a global instance of Vtable_ctrl
                     | storage in a global instance of Vtable_ctrl

Invocation of member function of Any will always relocate to functions in Vtable
*/

#pragma once

#include <gaa/wrap/std/any/any.hpp>