GAA_VARIANT_register_compact((double), Double)
    GAA_VARIANT_register_compact((std::string), String)
        GAA_VARIANT_register_compact((int), Integer)
            GAA_VARIANT_register_compact((char), Character)
                GAA_VARIANT_register_compact((bool), Logical)
                    GAA_VARIANT_register_compact((std::size_t), Index)