include(GNUInstallDirs)

install(DIRECTORY ${GAA_ROOT}/include/gaa DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
install(DIRECTORY ${GAA_ROOT}/3rd/include/boost DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
install(DIRECTORY ${GAA_ROOT}/3rd/include/eigen3 DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
install(TARGETS gaa 
    EXPORT gaaTargets    
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} 
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} 
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})