include(GNUInstallDirs)

install(DIRECTORY ${CMAKE_SOURCE_DIR}/include/gaa DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
install(TARGETS gaa 
    EXPORT gaaTargets    
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR} 
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} 
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})