function(gaaLinkExpCXX TARGET MODE)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        set(EXP_LIB "stdc++exp")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
        set(EXP_LIB "libc++experimental")
    else()
        message(STATUS "No experimental library for ${CMAKE_CXX_COMPILER_ID}")
        return()
    endif()

    set(GAA_LINK_WITH_CXX_EXP ON CACHE BOOL "Linked with C++ experimental library" FORCE)
    target_link_libraries(${TARGET} ${MODE} ${EXP_LIB})
    message(STATUS "Target ${TARGET} linked with ${EXP_LIB}")
endfunction()